apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "backend.fullname" . }}-config
  labels:
    {{- include "backend.labels" . | nindent 4 }}
data:
  DB_URL: "jdbc:postgresql://{{ .Values.env.database.host }}:{{ .Values.env.database.port }}/{{ .Values.env.database.name }}"
  SPRING_PROFILES_ACTIVE: "{{ .Values.env.springProfile }}"