replicaCount: 2

image:
  repository: 269809344861.dkr.ecr.eu-west-3.amazonaws.com/frontend-repo # Placeholder ECR
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80
  targetPort: 80

ingress:
  enabled: true
  hostname: "app.kolynois.com"
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip 
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443}]'
    alb.ingress.kubernetes.io/certificate-arn: "arn:aws:acm:eu-west-3:123456789012:certificate/xxx"