apiVersion: v1
kind: Secret
metadata:
  name: {{ include "backend.fullname" . }}-secret
  labels:
    {{- include "backend.labels" . | nindent 4 }}
type: Opaque
data:
  username: {{ .Values.env.database.username | b64enc | quote }}
  password: {{ .Values.env.database.password | b64enc | quote }}