import type { BmiResponse, BmiStatsItem } from "@/api/types";

const daysAgo = (days: number) => {
  const d = new Date();
  d.setDate(d.getDate() - days);
  return d.toISOString();
};

export const mockBmiResult: BmiResponse = {
  weight: 72,
  height: 175,
  bmi: 23.5,
  category: "NORMAL",
  label: "Poids normal",
  advice:
    "Excellent ! Continuez à maintenir une alimentation équilibrée et une activité physique régulière.",
  color: "#2ecc71",
  minIdealWeight: 56.7,
  maxIdealWeight: 76.3,
  calculatedAt: new Date().toISOString(),
};

export const mockHistory: BmiResponse[] = [
  {
    weight: 72,
    height: 175,
    bmi: 23.5,
    category: "NORMAL",
    label: "Poids normal",
    advice: "Excellent ! Continuez à maintenir une alimentation équilibrée.",
    color: "#2ecc71",
    minIdealWeight: 56.7,
    maxIdealWeight: 76.3,
    calculatedAt: daysAgo(0),
  },
  {
    weight: 74,
    height: 175,
    bmi: 24.2,
    category: "NORMAL",
    label: "Poids normal",
    advice: "Excellent ! Continuez à maintenir une alimentation équilibrée.",
    color: "#2ecc71",
    minIdealWeight: 56.7,
    maxIdealWeight: 76.3,
    calculatedAt: daysAgo(3),
  },
  {
    weight: 78,
    height: 175,
    bmi: 25.5,
    category: "OVERWEIGHT",
    label: "Surpoids",
    advice: "Léger surpoids. Augmentez votre activité physique.",
    color: "#f39c12",
    minIdealWeight: 56.7,
    maxIdealWeight: 76.3,
    calculatedAt: daysAgo(7),
  },
  {
    weight: 68,
    height: 175,
    bmi: 22.2,
    category: "NORMAL",
    label: "Poids normal",
    advice: "Excellent ! Continuez à maintenir une alimentation équilibrée.",
    color: "#2ecc71",
    minIdealWeight: 56.7,
    maxIdealWeight: 76.3,
    calculatedAt: daysAgo(14),
  },
  {
    weight: 58,
    height: 175,
    bmi: 18.9,
    category: "NORMAL",
    label: "Poids normal",
    advice: "Excellent ! Continuez à maintenir une alimentation équilibrée.",
    color: "#2ecc71",
    minIdealWeight: 56.7,
    maxIdealWeight: 76.3,
    calculatedAt: daysAgo(21),
  },
  {
    weight: 52,
    height: 175,
    bmi: 17.0,
    category: "UNDERWEIGHT",
    label: "Insuffisance pondérale",
    advice: "Votre poids est insuffisant. Consultez un nutritionniste.",
    color: "#3498db",
    minIdealWeight: 56.7,
    maxIdealWeight: 76.3,
    calculatedAt: daysAgo(28),
  },
  {
    weight: 85,
    height: 175,
    bmi: 27.8,
    category: "OVERWEIGHT",
    label: "Surpoids",
    advice: "Léger surpoids. Augmentez votre activité physique.",
    color: "#f39c12",
    minIdealWeight: 56.7,
    maxIdealWeight: 76.3,
    calculatedAt: daysAgo(35),
  },
  {
    weight: 95,
    height: 175,
    bmi: 31.0,
    category: "OBESE_CLASS_1",
    label: "Obésité modérée",
    advice: "Consultez un médecin pour un suivi personnalisé.",
    color: "#e67e22",
    minIdealWeight: 56.7,
    maxIdealWeight: 76.3,
    calculatedAt: daysAgo(42),
  },
];

export const mockStats: BmiStatsItem[] = [
  {
    category: "UNDERWEIGHT",
    count: 124,
    avgBmi: 17.2,
    minBmi: 14.1,
    maxBmi: 18.4,
  },
  {
    category: "NORMAL",
    count: 892,
    avgBmi: 21.8,
    minBmi: 18.5,
    maxBmi: 24.9,
  },
  {
    category: "OVERWEIGHT",
    count: 456,
    avgBmi: 27.1,
    minBmi: 25.0,
    maxBmi: 29.8,
  },
  {
    category: "OBESE_CLASS_1",
    count: 198,
    avgBmi: 32.4,
    minBmi: 30.0,
    maxBmi: 34.9,
  },
  {
    category: "OBESE_CLASS_2",
    count: 87,
    avgBmi: 37.2,
    minBmi: 35.0,
    maxBmi: 39.5,
  },
  {
    category: "OBESE_CLASS_3",
    count: 43,
    avgBmi: 42.8,
    minBmi: 40.0,
    maxBmi: 48.2,
  },
];
